# Generated by Django 3.2.25 on 2024-12-07 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuNombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('usuApellido', models.CharField(default='Sin Apellido', max_length=150, verbose_name='Apellido')),
                ('usuFechaNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('usuGenero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género')),
                ('usuTelefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('usuApodo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apodo')),
                ('usuPreferenciaAnuncios', models.BooleanField(default=False, verbose_name='Preferencia por Anuncios')),
                ('usuStatus', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Miembro del personal')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'webapp_usuario',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('carCodigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('carSubtotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('carIva', models.DecimalField(decimal_places=2, max_digits=9)),
                ('carTotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('carStatus', models.CharField(default='ACT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('carCodigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('carNombre', models.CharField(max_length=150)),
                ('carDescripcion', models.TextField()),
                ('carPrecio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('carFoto', models.ImageField(upload_to='carta/')),
                ('carStatus_1', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CartaCategoria',
            fields=[
                ('carxcatCodigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('carxcatNombre', models.CharField(max_length=150)),
                ('carxcatStatus', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('libCodigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('libNombre', models.CharField(max_length=150)),
                ('libAutor', models.CharField(max_length=150)),
                ('libFechaPublicacion', models.DateField()),
                ('libVolumen', models.IntegerField()),
                ('libSinopsis', models.TextField()),
                ('libURLLibro', models.URLField(blank=True, null=True)),
                ('libFoto', models.ImageField(upload_to='libros/')),
                ('libStatus', models.BooleanField(default=True)),
                ('libPrecio', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibroCategoria',
            fields=[
                ('libxcatCodigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('libxcatNombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioXCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuxcarFechaModificacion', models.DateTimeField(auto_now=True)),
                ('usuxcarStatus', models.CharField(default='ACT', max_length=3)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibrosXCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libxcarCantidad', models.PositiveIntegerField()),
                ('libxcarTotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='webapp.carrito')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.libro')),
            ],
        ),
        migrations.CreateModel(
            name='CartaXCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carxcarCantidad', models.PositiveIntegerField()),
                ('carxcarTotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carta', to='webapp.carrito')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.carta')),
            ],
        ),
        migrations.CreateModel(
            name='RelCartaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.carta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.cartacategoria')),
            ],
            options={
                'unique_together': {('carta', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='LibrosXLibreriaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.librocategoria')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.libro')),
            ],
            options={
                'unique_together': {('libro', 'categoria')},
            },
        ),
    ]
