# Generated by Django 3.2.25 on 2025-01-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='carStatus',
            field=models.CharField(default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='libro',
            name='libStatus',
            field=models.CharField(default='ACT', max_length=3),
        ),
    ]
