# Generated by Django 3.2.25 on 2025-01-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20250106_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='librocategoria',
            name='libxcatStatus',
            field=models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3),
        ),
    ]
